FROM openjdk:19-oracle as build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package


FROM openjdk:17-slim
COPY --from=build /home/app/target/LanchoneteAPI-0.0.1-SNAPSHOT.jar /usr/local/lib/LanchoneteAPI-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]