FROM openjdk:8-jdk-alpine

VOLUME /tmp

COPY target/LanchoneteAPI-0.0.1-SNAPSHOT.jar LanchoneteAPI-0.0.1-SNAPSHOT.jar

CMD [“java”,”-Djava.security.egd=file:/dev/./urandom”,”-jar”,”/LanchoneteAPI-0.0.1-SNAPSHOT.jar”]